language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.2.7
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2.2.7
    - rvm: jruby-head
env:
  - 'RSPEC_OPTIONS="--tag ~slow spec"'
  - 'RSPEC_OPTIONS="--tag slow spec/bidi/bidi_spec.rb spec/collation/collation_spec.rb"'
  - 'RSPEC_OPTIONS="--tag slow spec/collation/tailoring_spec.rb spec/collation/trie_dumps_spec.rb"'
  - 'RSPEC_OPTIONS="--tag slow spec/formatters/numbers/rbnf/rbnf_spec.rb"'
script: 'bundle exec rspec $RSPEC_OPTIONS'
before_install:
  - gem update --system 2.1.11
  - gem --version
  - sudo apt-get update -qq
  - sudo apt-get install -y libonig-dev
before_script: 'gem install bundler'
